<a href="https://colab.research.google.com/github/busragmsy/IoBDataAnalysis/blob/data-wrangling/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd
from datetime import datetime

# Fonksiyon: Belirli tarih aralığı için veri çek
def fetch_weather_data(start_date, end_date, latitude=41.03, longitude=28.84):
    url = f"https://archive-api.open-meteo.com/v1/archive?latitude={latitude}&longitude={longitude}&start_date={start_date}&end_date={end_date}&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,relative_humidity_2m_mean,windspeed_10m_max,winddirection_10m_dominant,cloudcover_mean&timezone=Europe%2FIstanbul"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()['daily']
        df = pd.DataFrame(data)
        df['datetime'] = pd.to_datetime(df['time'])  # Tarih sütunu ekle
        return df
    else:
        print(f"Hata: {response.status_code}")
        return None

# Yıl yıl çek ve birleştir (2012-2025)
years = range(2012, 2026)  # 2025 dahil
all_data = []

for year in years:
    start = f"{year}-01-01"
    end = f"{year}-12-31"
    df_year = fetch_weather_data(start, end)
    if df_year is not None:
        all_data.append(df_year)
    print(f"{year} yılı çekildi.")

# Tüm veriyi birleştir ve CSV'ye kaydet
if all_data:
    df_full = pd.concat(all_data, ignore_index=True)
    df_full.to_csv('istanbul_bagcilar_2012_2025_hava.csv', index=False)
    print("Tam veri 'istanbul_bagcilar_2012_2025_hava.csv' olarak kaydedildi.")
else:
    print("Veri çekilemedi.")

2012 yılı çekildi.
2013 yılı çekildi.
2014 yılı çekildi.
2015 yılı çekildi.
2016 yılı çekildi.
2017 yılı çekildi.
2018 yılı çekildi.
2019 yılı çekildi.
2020 yılı çekildi.
2021 yılı çekildi.
2022 yılı çekildi.
2023 yılı çekildi.
2024 yılı çekildi.
2025 yılı çekildi.
Tam veri 'istanbul_bagcilar_2012_2025_hava.csv' olarak kaydedildi.

In [ ]:
import requests
import pandas as pd

# Tam lokanta koordinatları
latitude = 41.04307772749923
longitude = 28.813459723655757

def fetch_hourly_weather(start_date, end_date):
    url = f"https://archive-api.open-meteo.com/v1/archive?latitude={latitude}&longitude={longitude}&start_date={start_date}&end_date={end_date}&hourly=temperature_2m,relative_humidity_2m,precipitation,rain,showers,snowfall,windspeed_10m,winddirection_10m,cloudcover,visibility&timezone=Europe%2FIstanbul"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()['hourly']
        df = pd.DataFrame(data)
        df['datetime'] = pd.to_datetime(df['time'])  # Saatlik datetime sütunu
        return df
    else:
        print(f"Hata: {response.status_code} - {response.text}")
        return None

# Yıl yıl çek (2012-2025)
years = range(2012, 2026)
all_data = []

for year in years:
    start = f"{year}-01-01"
    end = f"{year}-12-31"
    df_year = fetch_hourly_weather(start, end)
    if df_year is not None:
        all_data.append(df_year)
    print(f"{year} yılı saatlik veri çekildi.")

# Tüm veriyi birleştir ve CSV'ye kaydet
if all_data:
    df_full = pd.concat(all_data, ignore_index=True)
    df_full.to_csv('istanbul_bagcilar_tam_koordinat_2012_2025_saatlik_hava.csv', index=False)
    print("Saatlik CSV kaydedildi: istanbul_bagcilar_tam_koordinat_2012_2025_saatlik_hava.csv")
    print(f"Toplam satır sayısı: {len(df_full)} (yaklaşık 5.114 gün x 24 = ~122.736 kayıt)")
else:
    print("Veri çekilemedi.")

2012 yılı saatlik veri çekildi.
2013 yılı saatlik veri çekildi.
2014 yılı saatlik veri çekildi.
2015 yılı saatlik veri çekildi.
2016 yılı saatlik veri çekildi.
2017 yılı saatlik veri çekildi.
2018 yılı saatlik veri çekildi.
2019 yılı saatlik veri çekildi.
2020 yılı saatlik veri çekildi.
2021 yılı saatlik veri çekildi.
2022 yılı saatlik veri çekildi.
2023 yılı saatlik veri çekildi.
2024 yılı saatlik veri çekildi.
2025 yılı saatlik veri çekildi.
Saatlik CSV kaydedildi: istanbul_bagcilar_tam_koordinat_2012_2025_saatlik_hava.csv
Toplam satır sayısı: 122736 (yaklaşık 5.114 gün x 24 = ~122.736 kayıt)

In [ ]:
import requests
import pandas as pd

latitude = 41.04307772749923
longitude = 28.813459723655757

def fetch_hourly_weather(start_date, end_date):
    url = f"https://archive-api.open-meteo.com/v1/archive?latitude={latitude}&longitude={longitude}&start_date={start_date}&end_date={end_date}&hourly=temperature_2m,apparent_temperature,relative_humidity_2m,dewpoint_2m,precipitation,rain,showers,snowfall,windspeed_10m,winddirection_10m,cloudcover,visibility,uv_index,is_day,shortwave_radiation,pressure_msl&timezone=Europe%2FIstanbul"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()['hourly']
        df = pd.DataFrame(data)
        df['datetime'] = pd.to_datetime(df['time'])
        return df
    else:
        print(f"Hata: {response.status_code} - {response.text}")
        return None

# Yıl yıl çek (2012-2025)
years = range(2012, 2026)
all_data = []

for year in years:
    start = f"{year}-01-01"
    end = f"{year}-12-31"
    df_year = fetch_hourly_weather(start, end)
    if df_year is not None:
        all_data.append(df_year)
    print(f"{year} yılı saatlik veri çekildi.")

if all_data:
    df_full = pd.concat(all_data, ignore_index=True)
    df_full.to_csv('istanbul_bagcilar_tam_koordinat_2012_2025_saatlik_hava_genis.csv', index=False)
    print("Genişletilmiş saatlik CSV kaydedildi!")

2012 yılı saatlik veri çekildi.
2013 yılı saatlik veri çekildi.
2014 yılı saatlik veri çekildi.
2015 yılı saatlik veri çekildi.
2016 yılı saatlik veri çekildi.
2017 yılı saatlik veri çekildi.
2018 yılı saatlik veri çekildi.
2019 yılı saatlik veri çekildi.
2020 yılı saatlik veri çekildi.
2021 yılı saatlik veri çekildi.
2022 yılı saatlik veri çekildi.
2023 yılı saatlik veri çekildi.
2024 yılı saatlik veri çekildi.
2025 yılı saatlik veri çekildi.
Genişletilmiş saatlik CSV kaydedildi!

In [ ]:
import pandas as pd
import os

# Yerel dosya yolu
file_path = os.path.join('Veriler', 'CustomerData.csv')
df_tubitak = pd.read_csv(file_path)

print(f"Toplam satır: {len(df_tubitak):,}")
print(f"Sütunlar: {df_tubitak.columns.tolist()}\n")
print("Örnek satırlar:")
display(df_tubitak.head())

Toplam satır: 2,267,519
Sütunlar: ['MASANO', 'CEKNO', 'ACILIS_TARIHI', 'ACILIS_SAATI', 'KAPAMA_SAATI', 'TARIH', 'STOKADI', 'MIKTAR', 'SATIS_FIYATI']

Örnek satırlar:

,MASANO,CEKNO,ACILIS_TARIHI,ACILIS_SAATI,KAPAMA_SAATI,TARIH,STOKADI,MIKTAR,SATIS_FIYATI
0,02,3,2012-07-21 00:00:00.000,20:10,21:50,2012-07-21 00:00:00.000,FULL,1.0,7.0
1,P01,17,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,ICE TEA,1.0,2.5
2,P01,17,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,ICE TEA,1.0,2.5
3,P01,17,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,ICE TEA,1.0,2.5
4,P01,17,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,SODA,1.0,1.0

In [ ]:
import pandas as pd

# Dosya yolunu kendi yolunla değiştir (Colab'da sağ tıklayıp "Copy path" yapabilirsin)
file_path = '/content/drive/MyDrive/Colab Notebooks/TubitakIoB/TubitakVeriler.csv'

# Başlıksız oku
df = pd.read_csv(file_path, header=None)

# Sütun isimlerini ata (SQL sorguna göre tam eşleşme)
df.columns = [
    'MASANO',
    'ACILIS_TARIHI',
    'ACILIS_SAATI',
    'KAPAMA_SAATI',
    'TARIH',
    'STOKADI',
    'MIKTAR',
    'SATIS_FIYATI'
]

# İlk 5 satırı göster (kontrol için)
print("Başlık eklendikten sonra ilk 5 satır:")
display(df.head())

# Yeni başlıklı dosyayı kaydet
output_path = '/content/drive/MyDrive/Colab Notebooks/TubitakIoB/TubitakCustomerData.csv'
df.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"\nBaşlıklı dosya başarıyla kaydedildi: {output_path}")

Başlık eklendikten sonra ilk 5 satır:

,MASANO,ACILIS_TARIHI,ACILIS_SAATI,KAPAMA_SAATI,TARIH,STOKADI,MIKTAR,SATIS_FIYATI
0,02,2012-07-21 00:00:00.000,20:10,21:50,2012-07-21 00:00:00.000,FULL,1.0,7.0
1,02,2012-07-21 00:00:00.000,20:10,21:50,2012-07-21 00:00:00.000,NaN,NaN,NaN
2,P01,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,ICE TEA,1.0,2.5
3,P01,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,ICE TEA,1.0,2.5
4,P01,2012-07-23 00:00:00.000,11:32,11:46,2012-07-23 00:00:00.000,ICE TEA,1.0,2.5

Başlıklı dosya başarıyla kaydedildi: /content/drive/MyDrive/Colab Notebooks/TubitakIoB/TubitakCustomerData.csv

In [1]:
import pandas as pd
import os

file_path = os.path.join('Veriler', 'CustomerData.csv')

# 1. CSV'yi yükle
df = pd.read_csv(file_path)

# 2. Tarih-saat sütunlarını datetime'a çevir
df['acilis_datetime'] = pd.to_datetime(
    df['ACILIS_TARIHI'].astype(str).str[:10] + ' ' + df['ACILIS_SAATI'].astype(str),
    errors='coerce'
)
df['kapama_datetime'] = pd.to_datetime(
    df['ACILIS_TARIHI'].astype(str).str[:10] + ' ' + df['KAPAMA_SAATI'].astype(str),
    errors='coerce'
)

# Kapanış saati açılıştan küçükse gece yarısını geçmiş demektir → +1 gün
mask_overnight = df['kapama_datetime'] < df['acilis_datetime']
df.loc[mask_overnight, 'kapama_datetime'] += pd.Timedelta(days=1)

# Oturum süresi (dakika)
df['oturum_sure_dk'] = (df['kapama_datetime'] - df['acilis_datetime']).dt.total_seconds() / 60

# 3. Gruplama: MASANO + CEKNO + oturum bazında özet
df_grup = df.groupby(['MASANO', 'CEKNO', 'acilis_datetime', 'kapama_datetime', 'oturum_sure_dk']).agg(
    toplam_miktar  = ('MIKTAR',    'sum'),
    toplam_tutar   = ('SATIS_FIYATI', 'sum'),
    urun_sayisi    = ('STOKADI',   'nunique'),
    urun_listesi   = ('STOKADI',   lambda x: list(x.unique())),
).reset_index()

# 4. Masa grupları
# B → Bahçe | P → Paket | S → İç Salon | V → VIP | diğer → İç Salon
def masa_siniflandir(masano):
    harf = str(masano).strip().upper()[0]
    return {
        'B': 'Bahçe',
        'P': 'Paket',
        'S': 'İç Salon'
    }.get(harf, 'İç Salon')

df_grup['masa_grup'] = df_grup['MASANO'].apply(masa_siniflandir)

# 5. Zaman özellikleri
df_grup['tarih']       = df_grup['acilis_datetime'].dt.date
df_grup['saat']        = df_grup['acilis_datetime'].dt.hour
df_grup['gun_adi']     = df_grup['acilis_datetime'].dt.day_name()
df_grup['ay']          = df_grup['acilis_datetime'].dt.month
df_grup['yil']         = df_grup['acilis_datetime'].dt.year
df_grup['hafta_no']    = df_grup['acilis_datetime'].dt.isocalendar().week.astype(int)

# Hava verisi ile birleştirme anahtarı (en yakın tam saate yuvarla)
# Örnek: 12:45 → 13:00 | 12:14 → 12:00
df_grup['merge_saati'] = df_grup['acilis_datetime'].dt.round('h')

# 6. Kaydet
output_path = os.path.join('Veriler', 'grup_oturum_bazli_tubitak.csv')
df_grup.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"✓ Gruplama tamamlandı! {len(df_grup):,} oturum kaydedildi → {output_path}")
print(f"\nMasa grupları dağılımı:")
print(df_grup['masa_grup'].value_counts())
print(f"\nYıl dağılımı:")
print(df_grup['yil'].value_counts().sort_index())
print(f"\nİlk 5 satır:")
display(df_grup.head())

✓ Gruplama tamamlandı! 388,411 oturum kaydedildi → Veriler\grup_oturum_bazli_tubitak.csv

Masa grupları dağılımı:
masa_grup
İç Salon    171880
Paket       122015
Bahçe        94516
Name: count, dtype: int64

Yıl dağılımı:
yil
2012     7806
2013    22517
2014    28397
2015    33049
2016    34293
2017    32751
2018    33105
2019    34888
2020    28358
2021    34613
2022    32804
2023    30255
2024    27585
2025     7990
Name: count, dtype: int64

İlk 5 satır:

,MASANO,CEKNO,acilis_datetime,kapama_datetime,oturum_sure_dk,toplam_miktar,toplam_tutar,urun_sayisi,urun_listesi,masa_grup,tarih,saat,gun_adi,ay,yil,hafta_no,merge_saati
0,02,3,2012-07-21 20:10:00,2012-07-21 21:50:00,100.0,1.0,7.0,1,[FULL],İç Salon,2012-07-21,20,Saturday,7,2012,29,2012-07-21 20:00:00
1,333,69661,2015-04-13 18:01:00,2015-04-13 18:01:00,0.0,1.0,109.0,1,[SU],İç Salon,2015-04-13,18,Monday,4,2015,16,2015-04-13 18:00:00
2,B01,21,2012-07-23 12:00:00,2012-07-23 12:25:00,25.0,2.0,14.0,2,"[FULL, YARIM DOMATESSIZ]",Bahçe,2012-07-23,12,Monday,7,2012,30,2012-07-23 12:00:00
3,B01,41,2012-07-23 18:32:00,2012-07-23 18:36:00,4.0,2.0,9.5,2,"[ACISIZ SOGANSIZ, AYRAN]",Bahçe,2012-07-23,18,Monday,7,2012,30,2012-07-23 19:00:00
4,B01,67,2012-07-24 17:04:00,2012-07-24 17:20:00,16.0,4.0,19.0,2,"[AZ ACILI SOGANSIZ, SALGAM]",Bahçe,2012-07-24,17,Tuesday,7,2012,30,2012-07-24 17:00:00

In [ ]:
import pandas as pd
import os

# ── 1. Gruplandırılmış sipariş verisini yükle ────────────────────────────────
grup_path = os.path.join('Veriler', 'grup_oturum_bazli_tubitak.csv')
df_grup = pd.read_csv(grup_path, parse_dates=['acilis_datetime', 'kapama_datetime', 'merge_saati'])

# ── 2. Hava verisini yükle (Open-Meteo, saatlik) ────────────────────────────
hava_path = os.path.join('Veriler', 'hava-durumu2012-2025.csv')
df_hava = pd.read_csv(hava_path, parse_dates=['datetime'])

# Birleştirme anahtarı: hava verisi zaten tam saatlik, floor yeterli
df_hava['merge_saati'] = df_hava['datetime'].dt.floor('h')

# Boş sütunlar (visibility, uv_index) dahil edilmiyor
hava_cols = [
    'merge_saati',
    'temperature_2m',
    'apparent_temperature',
    'relative_humidity_2m',
    'dewpoint_2m',
    'precipitation',
    'rain',
    'showers',
    'snowfall',
    'windspeed_10m',
    'winddirection_10m',
    'cloudcover',
    'pressure_msl',
    'is_day',
    'shortwave_radiation',
]
df_hava_slim = df_hava[hava_cols].drop_duplicates('merge_saati')

# ── 3. Birleştir (left join) ─────────────────────────────────────────────────
df_merged = df_grup.merge(df_hava_slim, on='merge_saati', how='left')

# ── 4. Yağış kategorisi (7 seviye) ──────────────────────────────────────────
# snowfall: cm/h  |  rain/showers: mm/h  |  cloudcover: %
def yagis_kategori(row):
    snowfall   = row.get('snowfall',   0) or 0
    rain       = row.get('rain',       0) or 0
    showers    = row.get('showers',    0) or 0
    cloudcover = row.get('cloudcover', 0) or 0

    if snowfall >= 1:
        return 'Yoğun Kar'
    elif snowfall > 0:
        return 'Kar'
    elif rain > 5 or showers > 2:
        return 'Sağanak'
    elif rain > 0:
        return 'Yağmur'
    elif showers > 0:
        return 'Hafif Yağmur'
    elif cloudcover >= 75:
        return 'Bulutlu'
    else:
        return 'Açık'

df_merged['yagis_kategori'] = df_merged.apply(yagis_kategori, axis=1)

# ── 5. Sıcaklık aralığı ─────────────────────────────────────────────────────
df_merged['sicaklik_aralik'] = pd.cut(
    df_merged['temperature_2m'],
    bins=[-20, 0, 10, 20, 30, 50],
    labels=['Çok Soğuk (<0°)', 'Soğuk (0–10°)', 'Ilık (10–20°)', 'Sıcak (20–30°)', 'Çok Sıcak (>30°)']
)

# ── 6. Outlier flag ──────────────────────────────────────────────────────────
# Kayıtlar silinmiyor; analizde filtrelemek için işaretleniyor
# sifir_sureli : oturum süresi = 0 dk  (genellikle paket siparişleri)
# uzun_oturum  : oturum süresi > 240 dk (4 saatten uzun)
# None         : normal oturum
def outlier_flag(sure_dk):
    if sure_dk == 0:
        return 'sifir_sureli'
    elif sure_dk > 240:
        return 'uzun_oturum'
    return None

df_merged['outlier_flag'] = df_merged['oturum_sure_dk'].apply(outlier_flag)

# ── 7. Sıfır süreli oturumlar → Paket kontrolü ──────────────────────────────
sifir = df_merged[df_merged['outlier_flag'] == 'sifir_sureli']
print(f"=== Sıfır Süreli Oturum Kontrolü ===")
print(f"Toplam sıfır süreli oturum : {len(sifir):,}")
print(f"\nMasa grubu dağılımı:")
print(sifir['masa_grup'].value_counts().to_string())
paket_oran = (sifir['masa_grup'] == 'Paket').mean() * 100
print(f"\nPaket oranı (sıfır süreli içinde): %{paket_oran:.1f}")
print(f"\nPaket OLMAYAN sıfır süreli (ilk 10):")
print(sifir[sifir['masa_grup'] != 'Paket']
      [['MASANO', 'CEKNO', 'masa_grup', 'toplam_miktar', 'urun_listesi']]
      .head(10).to_string(index=False))

# ── 8. Outlier özeti ─────────────────────────────────────────────────────────
print(f"\n=== Outlier Özeti ===")
flag_ozet = df_merged['outlier_flag'].value_counts(dropna=False)
for k, v in flag_ozet.items():
    etiket = str(k) if k is not None else 'normal'
    print(f"  {etiket:20s}: {v:>7,}  (%{v/len(df_merged)*100:.1f})")

# ── 9. Müşteri davranış özeti (sadece normal oturumlar) ──────────────────────
df_normal = df_merged[df_merged['outlier_flag'].isna()]
print(f"\n=== Davranış Analizi (normal oturumlar: {len(df_normal):,}) ===")

DAVRANIS_METRIKLERI = dict(
    oturum_sayisi  = ('CEKNO',          'count'),
    ort_sure_dk    = ('oturum_sure_dk', 'mean'),
    ort_miktar     = ('toplam_miktar',  'mean'),
    ort_urun_cesit = ('urun_sayisi',    'mean'),
)

print("\n─── Yağış Koşuluna Göre Müşteri Davranışı ───")
print(df_normal.groupby('yagis_kategori', observed=True)
      .agg(**DAVRANIS_METRIKLERI)
      .round(2)
      .sort_values('oturum_sayisi', ascending=False)
      .to_string())

print("\n─── Sıcaklık Aralığına Göre Müşteri Davranışı ───")
print(df_normal.groupby('sicaklik_aralik', observed=True)
      .agg(**DAVRANIS_METRIKLERI)
      .round(2)
      .to_string())

print("\n─── Masa Grubuna Göre Müşteri Davranışı ───")
print(df_normal.groupby('masa_grup', observed=True)
      .agg(**DAVRANIS_METRIKLERI)
      .round(2)
      .sort_values('oturum_sayisi', ascending=False)
      .to_string())

# ── 10. Birleşik veriyi kaydet ───────────────────────────────────────────────
output_path = os.path.join('Veriler', 'oturum_hava_birlesik.csv')
df_merged.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"\nBirleşik dosya kaydedildi → {output_path}")
print(f"Sütunlar ({len(df_merged.columns)}): {df_merged.columns.tolist()}")

Birleştirme tamamlandı → Toplam kayıt: 388,411
  Hava eşleşen : 388,411
  Hava eksik   : 0
  Sütun sayısı : 33

─── Yağış Koşuluna Göre Müşteri Davranışı ───
                oturum_sayisi  ort_sure_dk  ort_miktar  ort_urun_cesit
yagis_kategori
Açık                   222001        49.53        5.88            3.37
Bulutlu                104243        53.03        5.90            3.35
Yağmur                  58221        57.90        5.87            3.34
Kar                      3662        53.06        5.99            3.26
Sağanak                   247        53.77        5.51            2.97
Yoğun Kar                  37        32.86        6.22            3.35

─── Sıcaklık Aralığına Göre Müşteri Davranışı ───
                  oturum_sayisi  ort_sure_dk  ort_miktar  ort_urun_cesit
sicaklik_aralik
Çok Soğuk (<0°)            1373        36.52        5.83            3.16
Soğuk (0–10°)             85623        51.55        5.89            3.30
Ilık (10–20°)            160667        51.92        5.91            3.36
Sıcak (20–30°)           130954        51.70        5.88            3.41
Çok Sıcak (>30°)           9794        53.67        5.63            3.32

─── Masa Grubuna Göre Müşteri Davranışı ───
           oturum_sayisi  ort_sure_dk  ort_miktar  ort_urun_cesit
masa_grup
İç Salon          171880        28.35        6.70            3.95
Paket             122015       100.17        4.40            2.19
Bahçe              94516        31.82        6.32            3.80

Birleşik dosya kaydedildi → Veriler\oturum_hava_birlesik.csv
Sütunlar (33): ['MASANO', 'CEKNO', 'acilis_datetime', 'kapama_datetime', 'oturum_sure_dk', 'toplam_miktar', 'toplam_tutar', 'urun_sayisi', 'urun_listesi', 'masa_grup', 'tarih', 'saat', 'gun_adi', 'ay', 'yil', 'hafta_no', 'merge_saati', 'temperature_2m', 'apparent_temperature', 'relative_humidity_2m', 'dewpoint_2m', 'precipitation', 'rain', 'showers', 'snowfall', 'windspeed_10m', 'winddirection_10m', 'cloudcover', 'pressure_msl', 'is_day', 'shortwave_radiation', 'yagis_kategori', 'sicaklik_aralik']